const periodictabledata =
[
    {
        name: "Hydrogen",
        atomicnumber: 1,
        symbol: "H",
        category: "Reactive nonmetal",
        atomicweight: "1.008",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 1,
        block: "s",
        row: 1,
        column: 1,
        visible: true
    },
    {
        name: "Helium",
        atomicnumber: 2,
        symbol: "He",
        category: "Noble gas",
        atomicweight: "4.0026",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 1,
        block: "s",
        row: 1,
        column: 18,
        visible: true
    },
    {
        name: "Lithium",
        atomicnumber: 3,
        symbol: "Li",
        category: "Alkali metal",
        atomicweight: "6.94",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 2,
        block: "s",
        row: 2,
        column: 1,
        visible: true
    },
    {
        name: "Beryllium",
        atomicnumber: 4,
        symbol: "Be",
        category: "Alkaline earth metal",
        atomicweight: "9.0122",
        occurrence: "",
        stateofmatter: "",
        group: 2,
        period: 2,
        block: "s",
        row: 2,
        column: 2,
        visible: true
    },
    {
        name: "Boron",
        atomicnumber: 5,
        symbol: "B",
        category: "Metalloid",
        atomicweight: "10.81",
        occurrence: "",
        stateofmatter: "",
        group: 13,
        period: 2,
        block: "p",
        row: 2,
        column: 13,
        visible: true
    },
    {
        name: "Carbon",
        atomicnumber: 6,
        symbol: "C",
        category: "Reactive nonmetal",
        atomicweight: "12.011",
        occurrence: "",
        stateofmatter: "",
        group: 14,
        period: 2,
        block: "p",
        row: 2,
        column: 14,
        visible: true
    },
    {
        name: "Nitrogen",
        atomicnumber: 7,
        symbol: "N",
        category: "Reactive nonmetal",
        atomicweight: "14.007",
        occurrence: "",
        stateofmatter: "",
        group: 15,
        period: 2,
        block: "p",
        row: 2,
        column: 15,
        visible: true
    },
    {
        name: "Oxygen",
        atomicnumber: 8,
        symbol: "O",
        category: "Reactive nonmetal",
        atomicweight: "15.999",
        occurrence: "",
        stateofmatter: "",
        group: 16,
        period: 2,
        block: "p",
        row: 2,
        column: 16,
        visible: true
    },
    {
        name: "Fluorine",
        atomicnumber: 9,
        symbol: "F",
        category: "Reactive nonmetal",
        atomicweight: "18.998",
        occurrence: "",
        stateofmatter: "",
        group: 17,
        period: 2,
        block: "p",
        row: 2,
        column: 17,
        visible: true
    },
    {
        name: "Neon",
        atomicnumber: 10,
        symbol: "Ne",
        category: "Noble gas",
        atomicweight: "20.18",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 2,
        block: "p",
        row: 2,
        column: 18,
        visible: true
    },
    {
        name: "Sodium",
        atomicnumber: 11,
        symbol: "Na",
        category: "Alkali metal",
        atomicweight: "22.99",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 3,
        block: "s",
        row: 3,
        column: 1,
        visible: true
    },
    {
        name: "Magnesium",
        atomicnumber: 12,
        symbol: "Mg",
        category: "Alkaline earth metal",
        atomicweight: "24.305",
        occurrence: "",
        stateofmatter: "",
        group: 2,
        period: 3,
        block: "s",
        row: 3,
        column: 2,
        visible: true
    },
    {
        name: "Aluminium",
        atomicnumber: 13,
        symbol: "Al",
        category: "Post-transition metal",
        atomicweight: "26.982",
        occurrence: "",
        stateofmatter: "",
        group: 13,
        period: 3,
        block: "p",
        row: 3,
        column: 13,
        visible: true
    },
    {
        name: "Silicon",
        atomicnumber: 14,
        symbol: "Si",
        category: "Metalloid",
        atomicweight: "28.085",
        occurrence: "",
        stateofmatter: "",
        group: 14,
        period: 3,
        block: "p",
        row: 3,
        column: 14,
        visible: true
    },
    {
        name: "Phosphorus",
        atomicnumber: 15,
        symbol: "P",
        category: "Reactive nonmetal",
        atomicweight: "30.974",
        occurrence: "",
        stateofmatter: "",
        group: 15,
        period: 3,
        block: "p",
        row: 3,
        column: 15,
        visible: true
    },
    {
        name: "Sulfur",
        atomicnumber: 16,
        symbol: "S",
        category: "Reactive nonmetal",
        atomicweight: "32.06",
        occurrence: "",
        stateofmatter: "",
        group: 16,
        period: 3,
        block: "p",
        row: 3,
        column: 16,
        visible: true
    },
    {
        name: "Chlorine",
        atomicnumber: 17,
        symbol: "Cl",
        category: "Reactive nonmetal",
        atomicweight: "35.45",
        occurrence: "",
        stateofmatter: "",
        group: 17,
        period: 3,
        block: "p",
        row: 3,
        column: 17,
        visible: true
    },
    {
        name: "Argon",
        atomicnumber: 18,
        symbol: "Ar",
        category: "Noble gas",
        atomicweight: "39.95",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 3,
        block: "p",
        row: 3,
        column: 18,
        visible: true
    },
    {
        name: "Potassium",
        atomicnumber: 19,
        symbol: "K",
        category: "Alkali metal",
        atomicweight: "39.098",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 4,
        block: "s",
        row: 4,
        column: 1,
        visible: true
    },
    {
        name: "Calcium",
        atomicnumber: 20,
        symbol: "Ca",
        category: "Alkaline earth metal",
        atomicweight: "40.078",
        occurrence: "",
        stateofmatter: "",
        group: 2,
        period: 4,
        block: "s",
        row: 4,
        column: 2,
        visible: true
    },
    {
        name: "Scandium",
        atomicnumber: 21,
        symbol: "Sc",
        category: "Transition metal",
        atomicweight: "44.956",
        occurrence: "",
        stateofmatter: "",
        group: 3,
        period: 4,
        block: "d",
        row: 4,
        column: 3,
        visible: true
    },
    {
        name: "Titanium",
        atomicnumber: 22,
        symbol: "Ti",
        category: "Transition metal",
        atomicweight: "47.867",
        occurrence: "",
        stateofmatter: "",
        group: 4,
        period: 4,
        block: "d",
        row: 4,
        column: 4,
        visible: true
    },
    {
        name: "Vanadium",
        atomicnumber: 23,
        symbol: "V",
        category: "Transition metal",
        atomicweight: "50.942",
        occurrence: "",
        stateofmatter: "",
        group: 5,
        period: 4,
        block: "d",
        row: 4,
        column: 5,
        visible: true
    },
    {
        name: "Chromium",
        atomicnumber: 24,
        symbol: "Cr",
        category: "Transition metal",
        atomicweight: "51.996",
        occurrence: "",
        stateofmatter: "",
        group: 6,
        period: 4,
        block: "d",
        row: 4,
        column: 6,
        visible: true
    },
    {
        name: "Manganese",
        atomicnumber: 25,
        symbol: "Mn",
        category: "Transition metal",
        atomicweight: "54.938",
        occurrence: "",
        stateofmatter: "",
        group: 7,
        period: 4,
        block: "d",
        row: 4,
        column: 7,
        visible: true
    },
    {
        name: "Iron",
        atomicnumber: 26,
        symbol: "Fe",
        category: "Transition metal",
        atomicweight: "55.845",
        occurrence: "",
        stateofmatter: "",
        group: 8,
        period: 4,
        block: "d",
        row: 4,
        column: 8,
        visible: true
    },
    {
        name: "Cobalt",
        atomicnumber: 27,
        symbol: "Co",
        category: "Transition metal",
        atomicweight: "58.933",
        occurrence: "",
        stateofmatter: "",
        group: 9,
        period: 4,
        block: "d",
        row: 4,
        column: 9,
        visible: true
    },
    {
        name: "Nickel",
        atomicnumber: 28,
        symbol: "Ni",
        category: "Transition metal",
        atomicweight: "58.693",
        occurrence: "",
        stateofmatter: "",
        group: 10,
        period: 4,
        block: "d",
        row: 4,
        column: 10,
        visible: true
    },
    {
        name: "Copper",
        atomicnumber: 29,
        symbol: "Cu",
        category: "Transition metal",
        atomicweight: "63.546",
        occurrence: "",
        stateofmatter: "",
        group: 11,
        period: 4,
        block: "d",
        row: 4,
        column: 11,
        visible: true
    },
    {
        name: "Zinc",
        atomicnumber: 30,
        symbol: "Zn",
        category: "Post-transition metal",
        atomicweight: "65.38",
        occurrence: "",
        stateofmatter: "",
        group: 12,
        period: 4,
        block: "d",
        row: 4,
        column: 12,
        visible: true
    },
    {
        name: "Gallium",
        atomicnumber: 31,
        symbol: "Ga",
        category: "Post-transition metal",
        atomicweight: "69.723",
        occurrence: "",
        stateofmatter: "",
        group: 13,
        period: 4,
        block: "p",
        row: 4,
        column: 13,
        visible: true
    },
    {
        name: "Germanium",
        atomicnumber: 32,
        symbol: "Ge",
        category: "Metalloid",
        atomicweight: "72.63",
        occurrence: "",
        stateofmatter: "",
        group: 14,
        period: 4,
        block: "p",
        row: 4,
        column: 14,
        visible: true
    },
    {
        name: "Arsenic",
        atomicnumber: 33,
        symbol: "As",
        category: "Metalloid",
        atomicweight: "74.922",
        occurrence: "",
        stateofmatter: "",
        group: 15,
        period: 4,
        block: "p",
        row: 4,
        column: 15,
        visible: true
    },
    {
        name: "Selenium",
        atomicnumber: 34,
        symbol: "Se",
        category: "Reactive nonmetal",
        atomicweight: "78.971",
        occurrence: "",
        stateofmatter: "",
        group: 16,
        period: 4,
        block: "p",
        row: 4,
        column: 16,
        visible: true
    },
    {
        name: "Bromine",
        atomicnumber: 35,
        symbol: "Br",
        category: "Reactive nonmetal",
        atomicweight: "79.904",
        occurrence: "",
        stateofmatter: "",
        group: 17,
        period: 4,
        block: "p",
        row: 4,
        column: 17,
        visible: true
    },
    {
        name: "Krypton",
        atomicnumber: 36,
        symbol: "Kr",
        category: "Noble gas",
        atomicweight: "83.798",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 4,
        block: "p",
        row: 4,
        column: 18,
        visible: true
    },
    {
        name: "Rubidium",
        atomicnumber: 37,
        symbol: "Rb",
        category: "Alkali metal",
        atomicweight: "85.468",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 5,
        block: "s",
        row: 5,
        column: 1,
        visible: true
    },
    {
        name: "Strontium",
        atomicnumber: 38,
        symbol: "Sr",
        category: "Alkaline earth metal",
        atomicweight: "87.62",
        occurrence: "",
        stateofmatter: "",
        group: 2,
        period: 5,
        block: "s",
        row: 5,
        column: 2,
        visible: true
    },
    {
        name: "Yttrium",
        atomicnumber: 39,
        symbol: "Y",
        category: "Transition metal",
        atomicweight: "88.906",
        occurrence: "",
        stateofmatter: "",
        group: 3,
        period: 5,
        block: "d",
        row: 5,
        column: 3,
        visible: true
    },
    {
        name: "Zirconium",
        atomicnumber: 40,
        symbol: "Zr",
        category: "Transition metal",
        atomicweight: "91.224",
        occurrence: "",
        stateofmatter: "",
        group: 4,
        period: 5,
        block: "d",
        row: 5,
        column: 4,
        visible: true
    },
    {
        name: "Niobium",
        atomicnumber: 41,
        symbol: "Nb",
        category: "Transition metal",
        atomicweight: "92.906",
        occurrence: "",
        stateofmatter: "",
        group: 5,
        period: 5,
        block: "d",
        row: 5,
        column: 5,
        visible: true
    },
    {
        name: "Molybdenum",
        atomicnumber: 42,
        symbol: "Mo",
        category: "Transition metal",
        atomicweight: "95.95",
        occurrence: "",
        stateofmatter: "",
        group: 6,
        period: 5,
        block: "d",
        row: 5,
        column: 6,
        visible: true
    },
    {
        name: "Technetium",
        atomicnumber: 43,
        symbol: "Tc",
        category: "Transition metal",
        atomicweight: "[97]",
        occurrence: "",
        stateofmatter: "",
        group: 7,
        period: 5,
        block: "d",
        row: 5,
        column: 7,
        visible: true
    },
    {
        name: "Ruthenium",
        atomicnumber: 44,
        symbol: "Ru",
        category: "Transition metal",
        atomicweight: "101.07",
        occurrence: "",
        stateofmatter: "",
        group: 8,
        period: 5,
        block: "d",
        row: 5,
        column: 8,
        visible: true
    },
    {
        name: "Rhodium",
        atomicnumber: 45,
        symbol: "Rh",
        category: "Transition metal",
        atomicweight: "102.91",
        occurrence: "",
        stateofmatter: "",
        group: 9,
        period: 5,
        block: "d",
        row: 5,
        column: 9,
        visible: true
    },
    {
        name: "Palladium",
        atomicnumber: 46,
        symbol: "Pd",
        category: "Transition metal",
        atomicweight: "106.42",
        occurrence: "",
        stateofmatter: "",
        group: 10,
        period: 5,
        block: "d",
        row: 5,
        column: 10,
        visible: true
    },
    {
        name: "Silver",
        atomicnumber: 47,
        symbol: "Ag",
        category: "Transition metal",
        atomicweight: "107.87",
        occurrence: "",
        stateofmatter: "",
        group: 11,
        period: 5,
        block: "d",
        row: 5,
        column: 11,
        visible: true
    },
    {
        name: "Cadmium",
        atomicnumber: 48,
        symbol: "Cd",
        category: "Post-transition metal",
        atomicweight: "112.41",
        occurrence: "",
        stateofmatter: "",
        group: 12,
        period: 5,
        block: "d",
        row: 5,
        column: 12,
        visible: true
    },
    {
        name: "Indium",
        atomicnumber: 49,
        symbol: "In",
        category: "Post-transition metal",
        atomicweight: "114.82",
        occurrence: "",
        stateofmatter: "",
        group: 13,
        period: 5,
        block: "p",
        row: 5,
        column: 13,
        visible: true
    },
    {
        name: "Tin",
        atomicnumber: 50,
        symbol: "Sn",
        category: "Post-transition metal",
        atomicweight: "118.71",
        occurrence: "",
        stateofmatter: "",
        group: 14,
        period: 5,
        block: "p",
        row: 5,
        column: 14,
        visible: true
    },
    {
        name: "Antimony",
        atomicnumber: 51,
        symbol: "Sb",
        category: "Metalloid",
        atomicweight: "121.76",
        occurrence: "",
        stateofmatter: "",
        group: 15,
        period: 5,
        block: "p",
        row: 5,
        column: 15,
        visible: true
    },
    {
        name: "Tellurium",
        atomicnumber: 52,
        symbol: "Te",
        category: "Metalloid",
        atomicweight: "127.6",
        occurrence: "",
        stateofmatter: "",
        group: 16,
        period: 5,
        block: "p",
        row: 5,
        column: 16,
        visible: true
    },
    {
        name: "Iodine",
        atomicnumber: 53,
        symbol: "I",
        category: "Reactive nonmetal",
        atomicweight: "126.9",
        occurrence: "",
        stateofmatter: "",
        group: 17,
        period: 5,
        block: "p",
        row: 5,
        column: 17,
        visible: true
    },
    {
        name: "Xenon",
        atomicnumber: 54,
        symbol: "Xe",
        category: "Noble gas",
        atomicweight: "131.29",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 5,
        block: "p",
        row: 5,
        column: 18,
        visible: true
    },
    {
        name: "Caesium",
        atomicnumber: 55,
        symbol: "Cs",
        category: "Alkali metal",
        atomicweight: "132.91",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 6,
        block: "s",
        row: 6,
        column: 1,
        visible: true
    },
    {
        name: "Barium",
        atomicnumber: 56,
        symbol: "Ba",
        category: "Alkaline earth metal",
        atomicweight: "137.33",
        occurrence: "",
        stateofmatter: "",
        group: 2,
        period: 6,
        block: "s",
        row: 6,
        column: 2,
        visible: true
    },
    {
        name: "Lanthanum",
        atomicnumber: 57,
        symbol: "La",
        category: "Lanthanide",
        atomicweight: "138.91",
        occurrence: "",
        stateofmatter: "",
        group: 3,
        period: 6,
        block: "d",
        row: 6,
        column: 3,
        visible: true
    },
    {
        name: "Cerium",
        atomicnumber: 58,
        symbol: "Ce",
        category: "Lanthanide",
        atomicweight: "140.12",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 4,
        visible: true
    },
    {
        name: "Praseodymium",
        atomicnumber: 59,
        symbol: "Pr",
        category: "Lanthanide",
        atomicweight: "140.91",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 5,
        visible: true
    },
    {
        name: "Neodymium",
        atomicnumber: 60,
        symbol: "Nd",
        category: "Lanthanide",
        atomicweight: "144.24",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 6,
        visible: true
    },
    {
        name: "Promethium",
        atomicnumber: 61,
        symbol: "Pm",
        category: "Lanthanide",
        atomicweight: "[145]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 7,
        visible: true
    },
    {
        name: "Samarium",
        atomicnumber: 62,
        symbol: "Sm",
        category: "Lanthanide",
        atomicweight: "150.36",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 8,
        visible: true
    },
    {
        name: "Europium",
        atomicnumber: 63,
        symbol: "Eu",
        category: "Lanthanide",
        atomicweight: "151.96",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 9,
        visible: true
    },
    {
        name: "Gadolinium",
        atomicnumber: 64,
        symbol: "Gd",
        category: "Lanthanide",
        atomicweight: "157.25",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 10,
        visible: true
    },
    {
        name: "Terbium",
        atomicnumber: 65,
        symbol: "Tb",
        category: "Lanthanide",
        atomicweight: "158.93",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 11,
        visible: true
    },
    {
        name: "Dysprosium",
        atomicnumber: 66,
        symbol: "Dy",
        category: "Lanthanide",
        atomicweight: "162.5",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 12,
        visible: true
    },
    {
        name: "Holmium",
        atomicnumber: 67,
        symbol: "Ho",
        category: "Lanthanide",
        atomicweight: "164.93",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 13,
        visible: true
    },
    {
        name: "Erbium",
        atomicnumber: 68,
        symbol: "Er",
        category: "Lanthanide",
        atomicweight: "167.26",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 14,
        visible: true
    },
    {
        name: "Thulium",
        atomicnumber: 69,
        symbol: "Tm",
        category: "Lanthanide",
        atomicweight: "168.93",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 15,
        visible: true
    },
    {
        name: "Ytterbium",
        atomicnumber: 70,
        symbol: "Yb",
        category: "Lanthanide",
        atomicweight: "173.05",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 16,
        visible: true
    },
    {
        name: "Lutenium",
        atomicnumber: 71,
        symbol: "Lu",
        category: "Lanthanide",
        atomicweight: "174.97",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 6,
        block: "f",
        row: 8,
        column: 17,
        visible: true
    },
    {
        name: "Hafnium",
        atomicnumber: 72,
        symbol: "Hf",
        category: "Transition metal",
        atomicweight: "178.49",
        occurrence: "",
        stateofmatter: "",
        group: 4,
        period: 6,
        block: "d",
        row: 6,
        column: 4,
        visible: true
    },
    {
        name: "Tantalum",
        atomicnumber: 73,
        symbol: "Ta",
        category: "Transition metal",
        atomicweight: "180.95",
        occurrence: "",
        stateofmatter: "",
        group: 5,
        period: 6,
        block: "d",
        row: 6,
        column: 5,
        visible: true
    },
    {
        name: "Tungsten",
        atomicnumber: 74,
        symbol: "W",
        category: "Transition metal",
        atomicweight: "183.84",
        occurrence: "",
        stateofmatter: "",
        group: 6,
        period: 6,
        block: "d",
        row: 6,
        column: 6,
        visible: true
    },
    {
        name: "Rhenium",
        atomicnumber: 75,
        symbol: "Re",
        category: "Transition metal",
        atomicweight: "186.21",
        occurrence: "",
        stateofmatter: "",
        group: 7,
        period: 6,
        block: "d",
        row: 6,
        column: 7,
        visible: true
    },
    {
        name: "Osmium",
        atomicnumber: 76,
        symbol: "Os",
        category: "Transition metal",
        atomicweight: "190.23",
        occurrence: "",
        stateofmatter: "",
        group: 8,
        period: 6,
        block: "d",
        row: 6,
        column: 8,
        visible: true
    },
    {
        name: "Iridium",
        atomicnumber: 77,
        symbol: "Ir",
        category: "Transition metal",
        atomicweight: "192.22",
        occurrence: "",
        stateofmatter: "",
        group: 9,
        period: 6,
        block: "d",
        row: 6,
        column: 9,
        visible: true
    },
    {
        name: "Platinum",
        atomicnumber: 78,
        symbol: "Pt",
        category: "Transition metal",
        atomicweight: "195.08",
        occurrence: "",
        stateofmatter: "",
        group: 10,
        period: 6,
        block: "d",
        row: 6,
        column: 10,
        visible: true
    },
    {
        name: "Gold",
        atomicnumber: 79,
        symbol: "Au",
        category: "Transition metal",
        atomicweight: "196.97",
        occurrence: "",
        stateofmatter: "",
        group: 11,
        period: 6,
        block: "d",
        row: 6,
        column: 11,
        visible: true
    },
    {
        name: "Mercury",
        atomicnumber: 80,
        symbol: "Hg",
        category: "Post-transition metal",
        atomicweight: "200.59",
        occurrence: "",
        stateofmatter: "",
        group: 12,
        period: 6,
        block: "d",
        row: 6,
        column: 12,
        visible: true
    },
    {
        name: "Thallium",
        atomicnumber: 81,
        symbol: "Tl",
        category: "Post-transition metal",
        atomicweight: "204.38",
        occurrence: "",
        stateofmatter: "",
        group: 13,
        period: 6,
        block: "p",
        row: 6,
        column: 13,
        visible: true
    },
    {
        name: "Lead",
        atomicnumber: 82,
        symbol: "Pb",
        category: "Post-transition metal",
        atomicweight: "207.2",
        occurrence: "",
        stateofmatter: "",
        group: 14,
        period: 6,
        block: "p",
        row: 6,
        column: 14,
        visible: true
    },
    {
        name: "Bismuth",
        atomicnumber: 83,
        symbol: "Bi",
        category: "Post-transition metal",
        atomicweight: "208.98",
        occurrence: "",
        stateofmatter: "",
        group: 15,
        period: 6,
        block: "p",
        row: 6,
        column: 15,
        visible: true
    },
    {
        name: "Polonium",
        atomicnumber: 84,
        symbol: "Po",
        category: "Post-transition metal",
        atomicweight: "[209]",
        occurrence: "",
        stateofmatter: "",
        group: 16,
        period: 6,
        block: "p",
        row: 6,
        column: 16,
        visible: true
    },
    {
        name: "Astatine",
        atomicnumber: 85,
        symbol: "At",
        category: "Metalloid",
        atomicweight: "[210]",
        occurrence: "",
        stateofmatter: "",
        group: 17,
        period: 6,
        block: "p",
        row: 6,
        column: 17,
        visible: true
    },
    {
        name: "Radon",
        atomicnumber: 86,
        symbol: "Rn",
        category: "Noble gas",
        atomicweight: "[222]",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 6,
        block: "p",
        row: 6,
        column: 18,
        visible: true
    },
    {
        name: "Francium",
        atomicnumber: 87,
        symbol: "Fr",
        category: "Alkali metal",
        atomicweight: "[223]",
        occurrence: "",
        stateofmatter: "",
        group: 1,
        period: 7,
        block: "s",
        row: 7,
        column: 1,
        visible: true
    },
    {
        name: "Radium",
        atomicnumber: 88,
        symbol: "Ra",
        category: "Alkaline earth metal",
        atomicweight: "[226]",
        occurrence: "",
        stateofmatter: "",
        group: 2,
        period: 7,
        block: "s",
        row: 7,
        column: 2,
        visible: true
    },
    {
        name: "Actinium",
        atomicnumber: 89,
        symbol: "Ac",
        category: "Actinide",
        atomicweight: "[227]",
        occurrence: "",
        stateofmatter: "",
        group: 3,
        period: 7,
        block: "d",
        row: 7,
        column: 3,
        visible: true
    },
    {
        name: "Thorium",
        atomicnumber: 90,
        symbol: "Th",
        category: "Actinide",
        atomicweight: "232.04",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 4,
        visible: true
    },
    {
        name: "Protactinium",
        atomicnumber: 91,
        symbol: "Pa",
        category: "Actinide",
        atomicweight: "231.04",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 5,
        visible: true
    },
    {
        name: "Uranium",
        atomicnumber: 92,
        symbol: "U",
        category: "Actinide",
        atomicweight: "238.03",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 6,
        visible: true
    },
    {
        name: "Neptunium",
        atomicnumber: 93,
        symbol: "Np",
        category: "Actinide",
        atomicweight: "[237]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 7,
        visible: true
    },
    {
        name: "Plutonium",
        atomicnumber: 94,
        symbol: "Pu",
        category: "Actinide",
        atomicweight: "[244]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 8,
        visible: true
    },
    {
        name: "Americium",
        atomicnumber: 95,
        symbol: "Am",
        category: "Actinide",
        atomicweight: "[243]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 9,
        visible: true
    },
    {
        name: "Curium",
        atomicnumber: 96,
        symbol: "Cm",
        category: "Actinide",
        atomicweight: "[247]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 10,
        visible: true
    },
    {
        name: "Berkelium",
        atomicnumber: 97,
        symbol: "Bk",
        category: "Actinide",
        atomicweight: "[247]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 11,
        visible: true
    },
    {
        name: "Californium",
        atomicnumber: 98,
        symbol: "Cf",
        category: "Actinide",
        atomicweight: "[251]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 12,
        visible: true
    },
    {
        name: "Einsteinium",
        atomicnumber: 99,
        symbol: "Es",
        category: "Actinide",
        atomicweight: "[252]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 13,
        visible: true
    },
    {
        name: "Fermium",
        atomicnumber: 100,
        symbol: "Fm",
        category: "Actinide",
        atomicweight: "[257]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 14,
        visible: true
    },
    {
        name: "Mendelevium",
        atomicnumber: 101,
        symbol: "Md",
        category: "Actinide",
        atomicweight: "[258]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 15,
        visible: true
    },
    {
        name: "Nobelium",
        atomicnumber: 102,
        symbol: "No",
        category: "Actinide",
        atomicweight: "[259]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 16,
        visible: true
    },
    {
        name: "Lawrencium",
        atomicnumber: 103,
        symbol: "Lr",
        category: "Actinide",
        atomicweight: "[266]",
        occurrence: "",
        stateofmatter: "",
        group: 0,
        period: 7,
        block: "f",
        row: 9,
        column: 17,
        visible: true
    },
    {
        name: "Rutherfordium",
        atomicnumber: 104,
        symbol: "Rf",
        category: "Transition metal",
        atomicweight: "[267]",
        occurrence: "",
        stateofmatter: "",
        group: 4,
        period: 7,
        block: "d",
        row: 7,
        column: 4,
        visible: true
    },
    {
        name: "Dubnium",
        atomicnumber: 105,
        symbol: "Db",
        category: "Transition metal",
        atomicweight: "[268]",
        occurrence: "",
        stateofmatter: "",
        group: 5,
        period: 7,
        block: "d",
        row: 7,
        column: 5,
        visible: true
    },
    {
        name: "Seaborgium",
        atomicnumber: 106,
        symbol: "Sg",
        category: "Transition metal",
        atomicweight: "[269]",
        occurrence: "",
        stateofmatter: "",
        group: 6,
        period: 7,
        block: "d",
        row: 7,
        column: 6,
        visible: true
    },
    {
        name: "Bohrium",
        atomicnumber: 107,
        symbol: "Bh",
        category: "Transition metal",
        atomicweight: "[270]",
        occurrence: "",
        stateofmatter: "",
        group: 7,
        period: 7,
        block: "d",
        row: 7,
        column: 7,
        visible: true
    },
    {
        name: "Hassium",
        atomicnumber: 108,
        symbol: "Hs",
        category: "Transition metal",
        atomicweight: "[269]",
        occurrence: "",
        stateofmatter: "",
        group: 8,
        period: 7,
        block: "d",
        row: 7,
        column: 8,
        visible: true
    },
    {
        name: "Meitnerium",
        atomicnumber: 109,
        symbol: "Mt",
        category: "Unknown",
        atomicweight: "[278]",
        occurrence: "",
        stateofmatter: "",
        group: 9,
        period: 7,
        block: "d",
        row: 7,
        column: 9,
        visible: true
    },
    {
        name: "Darmstadtium",
        atomicnumber: 110,
        symbol: "Ds",
        category: "Unknown",
        atomicweight: "[281]",
        occurrence: "",
        stateofmatter: "",
        group: 10,
        period: 7,
        block: "d",
        row: 7,
        column: 10,
        visible: true
    },
    {
        name: "Roentgenium",
        atomicnumber: 111,
        symbol: "Rg",
        category: "Unknown",
        atomicweight: "[282]",
        occurrence: "",
        stateofmatter: "",
        group: 11,
        period: 7,
        block: "d",
        row: 7,
        column: 11,
        visible: true
    },
    {
        name: "Copernicum",
        atomicnumber: 112,
        symbol: "Cn",
        category: "Post-transition metal",
        atomicweight: "[285]",
        occurrence: "",
        stateofmatter: "",
        group: 12,
        period: 7,
        block: "d",
        row: 7,
        column: 12,
        visible: true
    },
    {
        name: "Nihonium",
        atomicnumber: 113,
        symbol: "Nh",
        category: "Unknown",
        atomicweight: "[286]",
        occurrence: "",
        stateofmatter: "",
        group: 13,
        period: 7,
        block: "p",
        row: 7,
        column: 13,
        visible: true
    },
    {
        name: "Flerovium",
        atomicnumber: 114,
        symbol: "Fl",
        category: "Unknown",
        atomicweight: "[289]",
        occurrence: "",
        stateofmatter: "",
        group: 14,
        period: 7,
        block: "p",
        row: 7,
        column: 14,
        visible: true
    },
    {
        name: "Moscovium",
        atomicnumber: 115,
        symbol: "Mc",
        category: "Unknown",
        atomicweight: "[290]",
        occurrence: "",
        stateofmatter: "",
        group: 15,
        period: 7,
        block: "p",
        row: 7,
        column: 15,
        visible: true
    },
    {
        name: "Livermorium",
        atomicnumber: 116,
        symbol: "Lv",
        category: "Unknown",
        atomicweight: "[293]",
        occurrence: "",
        stateofmatter: "",
        group: 16,
        period: 7,
        block: "p",
        row: 7,
        column: 16,
        visible: true
    },
    {
        name: "Tennessine",
        atomicnumber: 117,
        symbol: "Ts",
        category: "Unknown",
        atomicweight: "[294]",
        occurrence: "",
        stateofmatter: "",
        group: 17,
        period: 7,
        block: "p",
        row: 7,
        column: 17,
        visible: true
    },
    {
        name: "Oganesson",
        atomicnumber: 118,
        symbol: "Og",
        category: "Unknown",
        atomicweight: "[294]",
        occurrence: "",
        stateofmatter: "",
        group: 18,
        period: 7,
        block: "p",
        row: 7,
        column: 18,
        visible: true
    },
]
